### PR TITLE
Fixed the external storage requester for android api version above 28

### PR DESCRIPTION
**Pull request by SergKhram**
https://github.com/allure-framework/allure-kotlin/issues/50
https://github.com/allure-framework/allure-kotlin/issues/43
type:bug

### CODE REVIEW

**Comment by SergKhram** [comment]
@viclovsky check this pull request, please

**Comment by viclovsky** [comment]
> @viclovsky check this pull request, please

Hi, @SergKhram  ! Thanks a lot for your PR. Please, sign Contributor License Agreement (https://github.com/allure-framework/allure-kotlin/pull/51#issuecomment-786439758).

**Comment by SergKhram** [comment]
> > @viclovsky check this pull request, please
> 
> 
> 
> Hi, @SergKhram  ! Thanks a lot for your PR. Please, sign Contributor License Agreement (https://github.com/allure-framework/allure-kotlin/pull/51#issuecomment-786439758).

I try , image, but after redirecting i see this message again

**Comment by SergKhram** [comment]
> > @viclovsky check this pull request, please
> 
> Hi, @SergKhram ! Thanks a lot for your PR. Please, sign Contributor License Agreement ([#51 (comment)](https://github.com/allure-framework/allure-kotlin/pull/51#issuecomment-786439758)).

Done!

**Comment by SergKhram** [comment]
@viclovsky ping

**Review by viclovsky — APPROVED** [review]
👍

**Pull request merged**
