### PR TITLE
Rft rename io.qameta.allure.kotlin to io.qameta.allure

### PR DESCRIPTION
**Pull request by viclovsky**
After discussion with @eroshenkoam  we made to conclusion that package names should stay as in allure-java.

### CODE REVIEW

**Comment by baev** [comment]
thats actually not a good idea since it may cause some resolution errors in case of having both java/kotlin dependencies in classpath.

**Comment by kamildziadek** [comment]
I agree with @baev on this one. Maven shouldn't have any artifacts with the same package. Having the same package can cause problems during dependency resolution (and I already know it will for some libraries, due to people copying the **allure-java-model** with the same package). 

I agree with the thought behind this, as it's generally not a good idea to put the language name in the package. Unfortunately, it's required here. When Kotlin came out many libraries started adding **kotlin** in the package name of established java libraries (like RxKotlin), and it worked great and didn't pose any problems so far. It's a cosmetic change that could pose problems, so it's not worth in my opinion.

The best solution would be to migrate the `allure-java` to Kotlin and expose it as a new version. Unfortunately, it requires a lot of effort and doesn't bring a lot of value at the moment. On top of that, there are slight differences in the API, so the migration wouldn't be seamless at all. The ideal solution would be to write next version of Allure Framework in Kotlin, but dunno if that's feasible at the moment.

**Comment by baev** [comment]
> The best solution would be to migrate the `allure-java` to Kotlin and expose it as a new version.

I don't think thats a good idea since majority of Allure users using Java as a main language. And from Java users perspective API that would be provided by Allure-Kotlin would be much less usable than current API designed on Java 8 baseline

From Kotlin users perspective we can improve Allure Java API usability (by providing nullability annotations and so on)

The only problem is that older Android versions isn't support Java 8 and some of language features we are using, so for Android it makes sense to have a separate module (and we even can merge all the modules into one called allure-android)

Am I missing something?

**Comment by viclovsky** [comment]
> thats actually not a good idea since it may cause some resolution errors in case of having both java/kotlin dependencies in classpath.

Is it really common case? My thought is that allure-kotlin is used for projects java less 1.8, for example, android frameworks but allure-java is used in all other cases.

**Comment by viclovsky** [comment]
The idea came up to me and @eroshenkoam and we wanted to discuss it. I am not insist on it.

**Comment by kamildziadek** [comment]
> I don't think thats a good idea since majority of Allure users using Java as a main language. And from Java users perspective API that would be provided by Allure-Kotlin would be much less usable than current API designed on Java 8 baseline

I don't know the API as well as you do, but I believe it look roughly the same. Java 8 features are not widely used in the public API (at least they were not in the modules that I have migrated). The additional features like aspects can be done using separate modules. 

>The only problem is that older Android versions isn't support Java 8 and some of language features we are using, so for Android it makes sense to have a separate module (and we even can merge all the modules into one called allure-android)
>
> Am I missing something?

It's not only Android that can leverage the `allure-kotlin`. This could also open the Allure to the world of Kotlin test frameworks like **Spek** or **kotest**. Those libraries tend to support Java 1.6+, so they won't be able to use `allure-java`. Moreover, having a Kotlin API is a bit better from the perspective of Kotlin users due to named parameters, lambdas, data classes, and stuff like that (it's only cosmetic though, but can improve usability).

That's why the `allure-kotlin` implementation with extra support for Java 8 features is generally better. The codebase is the shared and can be used more widely. But... it's not worth at the moment as `allure-java` is already well established and doesn't require any changes. That's just sth to consider for the next major release of allure framework.

**Comment by kamildziadek** [comment]
> > thats actually not a good idea since it may cause some resolution errors in case of having both java/kotlin dependencies in classpath.
> 
> Is it really common case? My thought is that allure-kotlin is used for projects java less 1.8, for example, android frameworks but allure-java is used in all other cases.

It's hard to tell how many times it will occur. It's definitely an edge case. But even if that would be 1, it's better to be protected from it at the very beginning, as after the release it's not sth that can be easily changed.

**Pull request closed without merging**
