### PR TITLE
Fix getInstrumentation() before super.onCreate runner, lazy obtain directory for test results (issue #67)

### PR DESCRIPTION
**Pull request by JacobKant**
try fixes issue #67

#### Checklist
- [x] [Sign Allure CLA][cla]
- [ ] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by J-Vegas** [comment]
hi! when it will be in release?

**Comment by J-Vegas** [comment]
hi. when it will be released?

**Comment by JacobKant** [comment]
@kamildziadek @viclovsky  can you do a code review? if you need something else for the merge, tell me

**Comment by apetrov322** [comment]
@kamildziadek @viclovsky ?

**Comment by J-Vegas** [comment]
@kamildziadek @viclovsky we still waiting

**Comment by viclovsky** [comment]
@JacobKant, could you please “Sign Allure CLA”:
https://github.com/allure-framework/allure-kotlin/pull/68#issue-1134174352

**Comment by JacobKant** [comment]
@viclovsky “Sign Allure CLA” checked

**Pull request merged**
