### PR TITLE
Issue 43 Permission requester for Android API > 28 (10 && 11 android os)

### PR DESCRIPTION
**Pull request by SergKhram**
#43

### CODE REVIEW

**Comment by SergKhram** [comment]
maybe need to add some javaops like 'auto RequestPermission' with default false?
False -> don't need to request
True -> need to request

**Comment by SergKhram** [comment]
@viclovsky check pls

**Comment by viclovsky** [comment]
> @viclovsky maybe need to add some javaops like 'autoRequestPermissions' with default false?
> False -> don't need to request
> True -> need to request

It is not critical. It might be made later, if it is necessary

**Comment by viclovsky** [comment]
> @viclovsky check pls

Looks good for me.

**Review by viclovsky — APPROVED** [review]
👍

**Pull request merged**
